### Test login
POST http://127.0.0.1:8000/dj-rest-auth/login/
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@mail.com",
    "password": "haslo12345"
}

### Test Registration
POST http://127.0.0.1:8000/dj-rest-auth/registration/
Content-Type: application/json

{
    "username": "Pata",
    "email": "pata@test.com",
    "password1": "haslo12345",
    "password2": "haslo12345"
}


### Test Fetch post list
GET http://127.0.0.1:8000/api/posts/
Content-Type: application/json